config/routes.rb
ReverseAuction::Application.routes.draw do

  devise_for :lawyers
  root 'static_pages#index'

  resources :questions
  resources :answers
  resources :lawyers, only: [:index, :show]

  match '/answers/new/:question_id', to: 'answers#new', via: 'get'

  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 10, maximum: 200 }
  validates :content, presence: true, length: { minimum: 200, maximum: 5000}
  validates :estimated_fee, presence: true, numericality: true
  validates :estimated_time, presence: true, length: { maximum: 30 }

  belongs_to :question
  belongs_to :lawyer
end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { minimum: 10, maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :registration_number, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :city, presence: true


  has_many :answers, dependent: :destroy

  def to_s
    "#{self.name}, #{self.city}, #{self.registration_number}"
  end

  def admin?
    self.admin
  end
end

app/models/question.rb
class Question < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 20, maximum: 150 }
  validates :content, presence: true, length: { minimum: 200, maximum: 5000}
  validates :city, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :phone, presence: true, length: { maximum: 12 }, numericality: true


  has_many :answers, dependent: :destroy

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_lawyer!
  before_action :ensure_admin, only: :destroy

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new(question_id: params[:question_id])
  end

  def create
    @answer = Answer.create(answer_params)
    @answer.lawyer_id = current_lawyer.id
    @answer.save
    flash[:notice] = 'Your answer was successfully created!'

    redirect_to question_path(@answer.question)
  end

  def destroy
    @answer = Answer.find(params[:id])
    @question = @answer.question
    @answer.destroy

    flash[:notice] = 'Answer deleted successfully!'
    redirect_to question_path(@question)
  end

  private
    def answer_params
      params.require(:answer).permit(:title, :content, :estimated_fee, :estimated_time, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def ensure_admin
    unless current_lawyer.admin?
      redirect_to root_url
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :registration_number << :address << :phone << :city
  end
end

app/controllers/lawyers_controller.rb
class LawyersController < ApplicationController

  def index
    @lawyers = Lawyer.paginate(page: params[:page])
  end

  def show
    @lawyer = Lawyer.find(params[:id])

    if (@lawyer.admin?)
      redirect_to root_url
    end

    if (@lawyer.nil?)
      flash[:alert] = 'Lawyer with #{params[:id]} not found.'
      redirect_to lawyers_path
    end

  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_lawyer!, only: [:edit, :update, :destroy]
  before_action :ensure_admin, only: [:edit, :update, :destroy]

  def index
    @questions = Question.paginate(page: params[:page], per_page: 10)
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create

    @question = Question.new(question_params)

    if verify_recaptcha(:model => @question, :message => "Oh! It's error with reCAPTCHA!") && @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :content, :city, :email, :phone)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def about
  end

  def help
  end

  def contact
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(title)
    base_title = app_name
    if title.empty?
      base_title
    else
      "#{base_title} | #{title}"
    end
  end

  def gravatar_for(user, options = { size: 100 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'img-responsive')
  end


  # takes a question and places its id to the 'new' action of the answers controller
  # for linking of question to answer

  def answer_url_maker(question)
      "/answers/new/#{question.id}"
  end


  # Defines application-wide setting for application name. Change the app-name once
  # to get it reflected all over the application.

  def app_name
    'Wakil Sahab'
  end
end

app/helpers/lawyers_helper.rb
module LawyersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/answers/_answer.html.erb
<div class="row">

  <div class="col-sm-2">
    <p><h3><%= answer.lawyer.name %></h3></p>
    <p><%= gravatar_for(answer.lawyer) %></p>
    <p>Location: <strong><%= answer.lawyer.city %></strong></p>
    <p>Phone: <strong><%= answer.lawyer.phone %></strong></p>
  </div>
  <div class="col-sm-10">
      <h3><%= answer.title %></h3>
      <p><%= answer.content %></p>
      <p><em><%= answer.lawyer.name %> posted this answer <%= time_ago_in_words(answer.created_at) %> ago.</em></p>
      <div class="alert alert-success" role="alert">Estimated Fee is <strong><%= answer.estimated_fee %></strong>. Estimated time: <strong><%= answer.estimated_time %></strong>. <div class="pull-right">Contact: <strong><%= answer.lawyer.phone %></strong></div></div>
  </div>
</div>
<div class="row" id="question_admin_toolbar">
  <div class="col-xs-8 col-xs-offset-2">
    <% if lawyer_signed_in? %>
        <% if current_lawyer.admin %>
            <%= link_to 'Delete', answer_path(answer), method: :delete, class:'btn btn-large btn-primary', data: { confirm: 'Are you sure?' } %>
        <% end %>
    <% end %>
  </div>
</div>
<hr />

app/views/answers/_form.html.erb
<h2>Your Answer</h2>
    <%= form_for @answer do |f| %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :content, rows: 5, cols: 50, class:"form-control" %>
        </div>

        <%= f.hidden_field :question_id%>

        <div class="form-group">
          <%= f.label 'Fee Estimate' %>
          <%= f.text_field :estimated_fee, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.label 'Estimated Time' %>
          <%= f.text_field :estimated_time, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit %>
        </div>
<% end %>

app/views/answers/new.html.erb
<h1>Please submit your answer to the question:</h1>
<h3><%= @question.title %></h3>
<blockquote><%= @question.content %></blockquote>
<div class="row"><%= render 'answers/form' %></div>

app/views/lawyers/index.html.erb
<div class="row">
  <% @lawyers.each do |lawyer| %>
      <div class="row">

        <div class="col-xs-2 col-xs-offset-1">
          <p>Lawyer ID: <%= lawyer.id %></p>
        </div>

        <div class="col-xs-3 col-xs-offset-1">
          <p><%= lawyer.name %></p>
        </div>


        <div class="col-xs-2 col-xs-offset-1">
          <p><%= lawyer.city %></p>
        </div>

        <div class="col-xs-2">
          <%= link_to 'View', lawyer_path(lawyer), class:'btn btn-primary btn-xs' %>
        </div>
      </div>
  <% end %>
  <div class="col-xs-5 col-xs-offset-5">
    <%= will_paginate @lawyers %>
  </div>


</div>

app/views/lawyers/show.html.erb
<div style="text-align: center;">
<div class="row">

    <h1><%= @lawyer.name %></h1>

</div>

<div class="row">

    <p>ID: <%= @lawyer.id %></p>
    <p>Name: <%= @lawyer.name %></p>
    <p>Registration Number: <%= @lawyer.registration_number %></p>
    <p>Address: <%= @lawyer.address %></p>
    <p>Phone: <%= @lawyer.phone %></p>

</div>

</div>

app/views/layouts/_bootstrap_includes.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

app/views/layouts/_devise_alerts.html.erb
<% if notice %>
    <div class="alert alert-warning" role="alert"><%= notice %></div>
<% end %>
<% if alert %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<div class="mastfoot">
  <div class="pull-right">
    <p><a href="http://www.wakilsahab.com">Wakil Sahab</a>, by <a href="http://www.aamirsayid.com">Aamir Sayid</a>. &copy; <%= Time.now.year %> All Rights Reserved</p>
  </div>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to app_name, root_path, class:'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Lawyers', lawyers_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>

            <% if lawyer_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_lawyer.name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Account Settings', edit_lawyer_registration_path %></li>
                    <li><%= link_to 'Sign out', destroy_lawyer_session_path, method: :delete %></li>
                  </ul>
                </li>
            <% else %>
                <li><%= link_to 'Sign in', new_lawyer_session_path %></li>
            <% end %>

          </ul>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= render 'layouts/bootstrap_includes' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="62XCx7O5SC6vtCBtxj_wwc74i1jKTooqFLRdOxPNUDE" />
</head>
<body data-no-turbolink>
<div class="container-fluid"><%= render 'layouts/navbar' %></div>

<div class="container">

  <%= render 'layouts/devise_alerts' %>

  <%= yield %>
  <%= debug(params) if Rails.env.development? %>

  <%= render 'layouts/footer' %>

  <!-- Analytics Codes -->
  <%= render 'shared/analytics' %>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

    <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
            <% @question.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

      <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, rows:6, class:"form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class:"form-control" %>
    </div>

      <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class:"form-control" %>
    </div>

      <div class="form-group">
      <%= f.label :phone %>
      <%= f.text_field :phone, class:"form-control" %>
    </div>

      <div class="form-group">
        <%= f.label 'Enter the code shown below:' %>
        <%= recaptcha_tags %>
      </div>

    <div class="form-group">
      <%= f.submit class:'btn btn-large btn-primary form-control' %>
    </div>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit question# <%= @question.id %></h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-5">
    <h1>Questions</h1>
    <p><%= link_to 'Submit your question', new_question_path, class:'btn btn-large btn-info' %></p>
  </div>
</div>
<hr />
<div class="row">
  <% @questions.each do |question| %>
    <div class="row">
        <div class="col-xs-2">
          <p>Question ID: <%= question.id %></p>
        </div>
        <div class="col-xs-7 col-xs-offset-1"><%= question.title %></div>
        <div class="col-xs-2">
          <%= link_to 'View', question_path(question), class:'btn btn-primary btn-xs' %>
        </div>
    </div>
  <% end %>
  <div class="col-xs-5 col-xs-offset-5">
    <%= will_paginate @questions %>
  </div>


</div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 style="text-align: center;">Post Your Question</h1>


    <%= render 'form' %>

    <%= link_to 'Back', questions_path %>
  </div>
</div>

app/views/questions/show.html.erb
<p>
  <h4>Question ID: <strong><%= @question.id %></strong></h4>
</p>
<h2 id="title">
   <%= @question.title %>
</h2>

<blockquote>
    <p><%= @question.content %></p>
</blockquote>
<p class="small">Someone from <strong><%= @question.city %></strong> asked <%= time_ago_in_words(@question.created_at) %> ago</p>

<hr />
<%= link_to 'Answer This', answer_url_maker(@question), class:'btn btn-lg btn-primary' %>
<% if lawyer_signed_in? %>
    <% if current_lawyer.admin? %>
        <%= link_to 'Edit', edit_question_path(@question), class:'btn btn-info btn-lg' %>
        <%= link_to 'Delete', question_path(@question), method: :delete, class:'btn btn-info btn-lg', data: {confirm: 'Are your sure?'} %>
    <% end %>
<% end %>

<hr />
<% if @question.answers.empty? %>
    <div class="alert alert-info" role="alert">There are no answers to this question yet! Please check again later.</div>
<% else %>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-5"><h1>Answers</h1></div>
    </div>
    <div class="row">
      <div class="col-md-12"><%= render @question.answers %></div>
    </div>
<% end %>

app/views/shared/_analytics.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-51321382-1', 'wakilsahab.com');
    ga('send', 'pageview');

</script>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About <%= app_name %></h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Welcome to <%= app_name %>!</h1>
  <p>Find the best lawyer for your problem. Get competitive pricing and time estimates from top lawyers of India.</p>
  <div class="btn-group">
    <p>
      <%= link_to 'Ask Question', new_question_path, class:"btn btn-primary btn-lg" %>
      <%= link_to 'Read All Questions', questions_path, class:"btn btn-success btn-lg" %>
      <%= link_to 'Check Status of Your Question', '#', class:"btn btn-info btn-lg" %>
    </p>
  </div>
</div>